### ISSUE TITLE
Google Fonts won't show up in Safari or Edge

### ISSUE THREAD

**Issue by patricia568** [patricia568/portfolio#8]
Hello @thomasjbradley ,

My fonts don't seem to be showing up in Safari or Edge, however they work perfectly fine in Chrome, Firefox, and Opera.

This is what my code looks like:
<img width="485" alt="Screenshot 2019-11-19 09 44 36" src="https://user-images.githubusercontent.com/31852223/69156406-5634a000-0ab1-11ea-9009-f296271a52c6.png">
<img width="711" alt="Screenshot 2019-11-19 09 45 02" src="https://user-images.githubusercontent.com/31852223/69156407-56cd3680-0ab1-11ea-8c26-3b416df577d1.png">

**Comment by thomasjbradley** [comment]
Can you take screenshots of what it should look like & what it looks like in Safari?
I want to confirm what I’m seeing is the same as what you’re seeing.

**Comment by patricia568** [comment]
This is what it's supposed to look like (looks like this in Chrome, Firefox, and Opera):
<img width="376" alt="Screenshot 2019-11-19 11 08 05" src="https://user-images.githubusercontent.com/31852223/69163915-0eb41100-0abd-11ea-84d3-01fabbdc3994.png">

And this is what it looks like in Safari and Edge:
<img width="376" alt="Screenshot 2019-11-19 11 08 28" src="https://user-images.githubusercontent.com/31852223/69163950-1a073c80-0abd-11ea-87e4-5d82d6fede52.png">

**Comment by thomasjbradley** [comment]
The Google Fonts aren’t connected in the HTML only Typekit fonts, on this line:
https://github.com/patricia568/portfolio/blob/master/_layouts/default.html#L20

**Comment by patricia568** [comment]
Ah silly me! It works now, thank you so much!
